### ISSUE TITLE
Migration to 0.11: errors of shared functions accross contracts

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cosmwasm-plus#103]
Facing the following error migrating errors to the new format (i.e. to 0.11):

```
53 | |         HandleMsg::Freeze {} => handle_freeze(deps, env),
   | |                                 ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `error::ContractError`, found enum `cw1_whitelist::error::ContractError`
```
This is because `handle_freeze()` is being imported from `cw1-whitelist`, which has its own `ContractError`.

Opening this issue so we can document / discuss solutions to this.

**Comment by webmaster128** [comment]
Here is an example of mixed type implementations: https://github.com/CosmWasm/cosmwasm/blob/v0.11.0-alpha3/contracts/staking/src/contract.rs#L56-L69

You use `?` like

```rust
HandleMsg::Freeze {} => Ok(handle_freeze(deps, env)?)
```

to convert `Result<Data, External>` to `Result<Data, Internal>`. For this to work you need an error converter: `impl From<External> for Internal`.

**Comment by maurolacy** [comment]
Thanks for the quick response! I'll try this and report back.

**Comment by maurolacy** [comment]
This worked, thanks. Still figuring out the best way to map one error into the other, but code now compiles.

**Comment by webmaster128** [comment]
> Still figuring out the best way to map one error into the other, but code now compiles.

At least for StdError -> custom error we now use the `thiserror` crate with something like

```rust
use cosmwasm_std::{CanonicalAddr, StdError};
use thiserror::Error;

// thiserror implements Display and ToString if you
// set the `#[error("…")]` attribute for all cases
#[derive(Error, Debug)]
pub enum MyCustomError {
    #[error("{0}")]
    // let thiserror implement From<StdError> for you
    Std(#[from] StdError),
    // this is whatever we want
    #[error("Permission denied: the sender is not the current owner")]
    NotCurrentOwner {
        expected: CanonicalAddr,
        actual: CanonicalAddr,
    },
    #[error("Messages empty. Must reflect at least one message")]
    MessagesEmpty,
}
```

However, I don't know how this will look like if you need multiple of those container cases.
