### ISSUE TITLE
Remove dependency between cw20_escrow and cw20_atomic_swap

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#115]
There is an import in the escrow contract: `use cw20_atomic_swap::balance::Balance;`

We should be able to  `use cw0::Balance`

Also, see if there is anything else to de-dup.

**Comment by maurolacy** [comment]
Just to be clear, for that I would have to move `Balance` (which is an enum for native and cw20 balances) to `cw0`. That would introduce dependency of `cw0` in `cw20`.

I'm OK with that, but want to confirm first. Maybe it's better to introduce another mod / namespace for these mixed structs.

**Comment by maurolacy** [comment]
#118. I think it's not bad to put there, as `cw20` is built on top of `cw0` so, it makes sense.
`cw20` also lacks a `balance` mod so, we're all happy now.

**Comment by ethanfrey** [comment]
You are right... the native coin Balance was already in cw0, but this was a different one.

Great job placing it in cw20 in spite of my comment. Very clean
