### ISSUE TITLE
Add cw20 support to token-weighted group

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#143]
Builds on #142 

The previous issue only supported native tokens. Extend this to support either one native denom or one cw20 address - set in init. Try for yourself which is the best code reuse - if it is easier to make 2 different contracts, one native-only and one cw20-only and share some group logic between them, that is also fine. Any given contract instance should only take either native coins or cw20 coins, so they don't need both code paths in the contract - think about making this maintainable and bug-free.

----

Here is a breakdown of the steps needed:

- [x] Use [`cw20::Balance`](https://github.com/CosmWasm/cosmwasm-plus/blob/666f265a8bdc4c9c6d47c3094a5edfa320a91bc7/packages/cw20/src/balance.rs#L11-L14) instead of `String` for [`InitMsg::denom`](https://github.com/CosmWasm/cosmwasm-plus/blob/ec45a73aad77f36d74ca23aeef77b472fe7de7e2/contracts/cw4-stake/src/msg.rs#L11) and [`Config::denom`](https://github.com/CosmWasm/cosmwasm-plus/blob/ec45a73aad77f36d74ca23aeef77b472fe7de7e2/contracts/cw4-stake/src/state.rs#L15)
- [x] [Change `handle_bond`](https://github.com/CosmWasm/cosmwasm-plus/blob/f9b41f8fbe5a0125dec1b07a53852b439edef801/contracts/cw4-stake/src/contract.rs#L67-L71) to accept native of cw20 balance. That means accepting `sender: HumanAddr, amount: cw20::Balance` instead of `info: MessageInfo`. This conversion should be done in the [`handle` switch](https://github.com/CosmWasm/cosmwasm-plus/blob/f9b41f8fbe5a0125dec1b07a53852b439edef801/contracts/cw4-stake/src/contract.rs#L61) just like in [`cw20-escrow`](https://github.com/CosmWasm/cosmwasm-plus/blob/34c26d42c2958e770c78b3e091cdf6a0503f0235/contracts/cw20-escrow/src/contract.rs#L38)
- [x] `handle_bond` should enforce incoming tokens using a switch on `config.denom`, inspired by [`cw20-escrow` checks](https://github.com/CosmWasm/cosmwasm-plus/blob/34c26d42c2958e770c78b3e091cdf6a0503f0235/contracts/cw20-escrow/src/contract.rs#L78-L93). You will want to keep the [current logic](https://github.com/CosmWasm/cosmwasm-plus/blob/f9b41f8fbe5a0125dec1b07a53852b439edef801/contracts/cw4-stake/src/contract.rs#L74-L90) for the Balance::Native case (or simplify it to use [`cw0::must_pay`](https://github.com/CosmWasm/cosmwasm-plus/blob/8acbab46558a8408af60fb6b2ba65299767e63bd/packages/cw0/src/payment.rs#L13-L36) if you know how to extend the custom error type.
- [x] [Update `handle_claim`](https://github.com/CosmWasm/cosmwasm-plus/blob/f9b41f8fbe5a0125dec1b07a53852b439edef801/contracts/cw4-stake/src/contract.rs#L216-L224) to release either native token (as now) or cw20-token (this can be `unimplemented!()` now, but have the branch based on the `cw20::Balance` variant)
- [x] Ensure all current tests pass with minor changes (just wrapping the denom in `cw20::Balance::Native`. You have laid the groundwork, but still have no cw20 support.
- [x] Add a `HandleMsg::Receive` variant to receive cw20 tokens. It should look similar to [`cw20-escrow::ReceiveMsg`](https://github.com/CosmWasm/cosmwasm-plus/blob/34c26d42c2958e770c78b3e091cdf6a0503f0235/contracts/cw20-escrow/src/msg.rs#L31-L43), but the ReceiveMsg should only handle the bond case, like `pub enum HandleMsg { Bond {} }`. The `Receive` interface is explained in the [cw20 spec](https://github.com/CosmWasm/cosmwasm-plus/blob/master/packages/cw20/README.md#receiver)
- [x] You need to update `handle` to process this `Receive` variant. If it is properly formatted, it should call into `handle_bond` using a `cw20::Balance::Cw20` token rather than `cw20::Balance::Native`. You can refer to the [`cw20-escrow` receive switch](https://github.com/CosmWasm/cosmwasm-plus/blob/34c26d42c2958e770c78b3e091cdf6a0503f0235/contracts/cw20-escrow/src/contract.rs#L43-L64).
- [ ] You can test instantiating a contract with cw20 support and properly bonding. For this, just mock out the receive call. (You can also try  [`cw-multi-test`](https://github.com/CosmWasm/cosmwasm-plus/tree/9e9518c027dd6afc086d95f04f380095c791d50a/packages/multi-test) to test a multi-contract setup, but that is still very undocumented. Use at you own risk.
- [ ] Now, go back to `handle_claim` and ensure it emits the proper withdraw message when the `config.denom` is `cw20::Balance::Cw20`.
- [ ] Add end-to-end tests for a cw20-supporting contract: bonding, unbonding, claiming. If you can query the membership value in the bonded group, there is no need to test voting or anything else, just that the membership is properly updated.

**Comment by juggernaut09** [comment]
Working on it.
