### ISSUE TITLE
Asymmetries between query and execute in CW1 (subkeys)

### ISSUE THREAD

**Issue by willclarktech** [CosmWasm/cosmwasm-plus#145]
I noticed there are a couple of asymmetries between query and execute in the CW1 contract:
1. Why is it called `CanSend` rather than `CanExecute`?
1. Since `Execute` takes a vector of msgs why wouldn't `CanSend` also take a vector?

**Comment by maurolacy** [comment]
You're right. The query name `CanSend` is probably for historical reasons. It would be better called `CanExecute`, as you say.
Regarding `CanExecute` accepting a vector of msgs, that's a nice improvement.

I'll implement the suggested changes.

**Comment by ethanfrey** [comment]
I believe this can be closed.

The name was modified as requested, and we decided not to support mutliple messages in the query
