### ISSUE TITLE
Add ContractAddr generic helper

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#153]
Based on discussion from https://github.com/CosmWasm/cosmwasm-plus/pull/150#discussion_r535873511

Add `pub type ContractAddr(pub HumanAddr)` to cw0, with some common functions to create messages and make queries, as well as 

Rename `Cw4Contract` to `Cw4ContractAddr`, and extend `ContractAddr` functionality. See if the refactoring simplifies the implementation. If not, we can just do the rename without adding some `ContractAddr` type (I am not sure if it would make anything easier).

If this simplifies things, do the same for the other helpers (cw3, cw20, cw721?).

**Comment by ethanfrey** [comment]
Note, looking more at the helpers, I am unsure if this extra type will help much. It may allow us to de-dup `encode_msg`, `encode_smart_query` and `encode_raw_query` helper methods, but the creation may be more work. eg we have to implement `From<HumanAddr>` to avoid ugly init: `let addr = Cw4ContractAddr(ContractAddr(msg.contract));` and rather use: `let addr = Cw4ContractAddr::from(msg.contract)`

**Comment by ethanfrey** [comment]
I would close this unless you still think this is valuable.

**Comment by maurolacy** [comment]
I agree this is OK as such.
