### ISSUE TITLE
Distinguish between weight 0 and not member in cw3 queries

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#154]
`Cw3QueryMsg::Voter{addr: HumanAddr}` should return something like `cw4::MemberResponse`, eg:

```rust
pub struct VoterInfo {
  pub weight: Option<u64>,
}
```

Do not change the `VoterListResponse` return info.

**Comment by maurolacy** [comment]
> Do not change the `VoterListResponse` return info.

Hmm, I see now that I missed that restriction. In any case, re-open and I'll revisit this: basically, using two different (sub)structs for `VoterResponse` and `VoterListResponse`.

**Comment by ethanfrey** [comment]
I missed that too just looking at the diff.

The member list always has a value, to avoid needless unwraps

**Comment by maurolacy** [comment]
Take a look at #159, and sorry for the confusion.
