### ISSUE TITLE
Support PartialEq on error

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#179]
Note: this is a long background process. Let's update contracts one by one as we refactor them (a bit like updating them all to storage-plus)

With `StdError::PartialEq` implementation from https://github.com/CosmWasm/cosmwasm/pull/662, we can replace lots of statements like:

```rust
        match err {
            ContractError::Unauthorized {} => {}
            e => panic!("Unexpected error: {}", e),
        }
```

with simpler statements like:

```rust
assert_eq!(ContractError::Unauthorized {}, err);
```

It requires `#[derive(PartialEq)]` on `ContractError` and the above-mentioned support for `StdError`

Contracts to update:

- [x] cw1-subkeys
- [x] cw1-whitelist
- [x] cw3-fixed-multisig
- [x] cw3-flex-multisig
- [x] cw4-group
- [x] cw4-stake
- [x] cw20-atomic-swap
- [x] cw20-base
- [x] cw20-bonding
- [x] cw20-escrow
- [x] cw20-staking
- [x] cw721-base

**Comment by ethanfrey** [comment]
This works now, and we just need to update the contract code to use it.
I will add a bunch of checkboxes and tick them off as I port the contract code (I did a few during other refactorings)

**Comment by maurolacy** [comment]
Are you still working on this, or should I take it from here?

**Comment by ethanfrey** [comment]
Thanks for taking this over. I started but then left it. Your PR looks nice.
