### ISSUE TITLE
Storage-plus: See if we can simplify PkOwned to Vec<u8>

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#199]
Is there a reason why we don't use that directly like `&[u8]`. Maybe an oversight when I wrote this API?

Then we can just return `Vec<u8>` than forcing wrapping.

**Comment by maurolacy** [comment]
Using `&[u8]` or `&str` directly _might_ be possible, but will require to carefully track and fix lifetime conficts first.

A simpler way seems to be implementing needed traits (`PrimaryKey`, `Prefixer`, probably others) directly for `Vec[u8]`, and remove `PkOwned` entirely.

**Comment by maurolacy** [comment]
Created #233 to track / fix the lifetimes issue.
