### ISSUE TITLE
Implement atomic swap contract with native tokens

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#26]
This should be a basic contract that implements one half of [the IOV atomic swap spec](https://github.com/iov-one/iov-core/blob/master/docs/atomic-swap-protocol-v1.md). There is also a [Solidity implementation of atomic swap](https://github.com/iov-one/ethereum-smart-contracts/blob/master/contracts/AtomicSwapEther.sol) as well as [one that supports ERC20 tokens](https://github.com/iov-one/ethereum-smart-contracts/blob/master/contracts/AtomicSwapERC20.sol), so creating such a contract allows any CosmWasm-based chain to swap tokens with an Ethereum-based chain, possibly on some off-chain DEX or just "over the counter". 

Create one contract that can handle and track many atomic swaps. Each swap has a unique ID and can store some tokens when it is created. Its balance cannot be adjusted after that fact, until it is either claimed or aborted (when the swap is closed and the funds go to a recipient).

For the first step, this should just handle native tokens that are sent along with the "create swap" message (see `env.msg.sent_funds`), and these can be distributed with `BankMsg::Send`.

You can start with with `cosmwasm-template`, but as the various contracts in this package are rather customized, it might make sense to copy eg. `cw20-escrow` as a start and then modify it heavily.

Please cover it with reasonable unit tests. You can look at [this integration test](https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/integrationtests/atomicswap.spec.ts#L229-L360) to get an idea of a successful end-to-end flow. For this contract, it would be nice to break it up into smaller pieces. Note it should be able to create both sides of the swap on the same contract and resolve them.

**Comment by ethanfrey** [comment]
@maurolacy I was doing cleanup and stubled upon https://github.com/CosmWasm/cosmwasm-examples/pull/2 which is when I started an atomic swap contract in Jan/Feb. The code uses a much older version of CosmWasm, but the key logic is the same. Maybe you can copy some stuff from that (I'm closing that PR)

**Comment by maurolacy** [comment]
OK, I've done an initial implementation. Basically copying `cw20-escrow` as you suggest, and adapting from your `cosmwasm-examples` atomic-swap branch.

I guess you'll want / prefer to have `HandleMsg::Create` functionality, a la `cw20-escrow`. I'll do that next.

In case you want to take a look, code is pushed in [https://github.com/CosmWasm/cosmwasm-plus/tree/atomic-swap](https://github.com/CosmWasm/cosmwasm-plus/tree/atomic-swap). Didn't make a pull request, as code is still pretty basic, no unit tests yet, etc.
