### ISSUE TITLE
Add cw20 support to atomic swap contract

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#27]
Builds on #26

Just like `cw20-escrow` supports both native tokens and cw20 tokens (via `Receive`), the atomic swap contract should be extended with this. We do not want a `TopUp` like `cw20-escrow`, but the creation via [direct function call](https://github.com/CosmWasm/cosmwasm-plus/blob/master/contracts/cw20-escrow/src/contract.rs#L56-L88) or via the [cw20::Receive entry point](https://github.com/CosmWasm/cosmwasm-plus/blob/master/contracts/cw20-escrow/src/contract.rs#L90-L123) serve as a useful model on how to implement this.

To test it, try swaping a native token vs a cw20 token using the same CosmWasm contract for both sides.

Once completed we can swap any native or cw20 token against eth or any erc20 token. Well.. we would need a UI for that, but the contracts are ready.

**Comment by maurolacy** [comment]
Initial implementation is under the [cw20-atomic-swaps](https://github.com/CosmWasm/cosmwasm-plus/tree/cw20-atomic-swaps) branch. Unit tests to follow; PR to follow after it.

I implemented functionality for the two tokens (native vs. cw20) into the same functions, for simplicity and consistency. Can separate them into different functions for clarity, if you think it would be better.

**Comment by maurolacy** [comment]
There are some `FIXME?` in the code: basically, what if somebody sents a non-empty array of native coins, or a cw20 coin, but sets their amounts to zero? Do we need to check / reject those messages? Or are they rejected by the SDK?

Another question: Do I need to improve the logs? Log the sender and amounts on creation, by example.

**Comment by maurolacy** [comment]
PR: #72.

**Comment by ethanfrey** [comment]
Counting zero amounts as missing is a good check. I would filter out zeros in the native coins, and then ensure it has length >0 and only save the filtered list.

For cw20 coins, yeah, rejecting 0 amounts sounds good. We should also reject such sends in cw20-base. Can you make an issue for that?

**Comment by maurolacy** [comment]
Sure. #76 created.

**Comment by ethanfrey** [comment]
Closed by #72
