### ISSUE TITLE
CW20 example contract which 1-to-1 mapped to native token

### ISSUE THREAD

**Issue by yihuang** [CosmWasm/cosmwasm-plus#276]
## Messages

- deposit message that lock native token and mint same amount of cw20 token
- withdraw message that burn cw20 token and release native token
- other standard cw20 messages.

## Purpose
- Some contract only works with cw20 token because of approval functionality, this will enable user to use native token as well.

**Comment by ethanfrey** [comment]
The cw20-bonding curve with a constant price and no exit tax should work for this use-case.
You could try that locally to start.

If you think there is a larger case for a simple contract to just do this, then I am open for a PR. It would be nice to have some discussion on this (wrap native -> cw20. what about cw20 -> native? we kind of do that over IBC now, but is this an important case?)

**Comment by yihuang** [comment]
> The cw20-bonding curve with a constant price and no exit tax should work for this use-case.
> You could try that locally to start.

cw20-bonding seems to do what I want. 👍
> 
> If you think there is a larger case for a simple contract to just do this, then I am open for a PR. It would be nice to have some discussion on this (wrap native -> cw20. what about cw20 -> native? we kind of do that over IBC now, but is this an important case?)

I can think of some use cases for `cw20 -> native`, for example to use cw20 in native [liquidity](https://github.com/tendermint/liquidity) module, or use ibc-transfer with cw20 tokens?

**Comment by ethanfrey** [comment]
Can I close this issue?
Does the bonding contract work well enough, or would you prefer a custom contract for this use case?
(I am happy to leave the issue open and accept a PR, but doubt I will get around to that anytime soon)

**Comment by yihuang** [comment]
I think the bonding contract work well, closing now.
