### ISSUE TITLE
`Sudo` over no `new_with_sudo` contract wrapper error message

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cosmwasm-plus#278]
In the multi-test context, to send the `Sudo` message to a contract requires creating the contract wrapper with `new_with_sudo`.
This is obvious, but when you forget to do it, the resulting error message is not clear / obvious at all:
```rust
`Result::unwrap()` on an `Err` value: "Error parsing into type alloc::string::String: Invalid type"
```

Consider improving on the error message, so a contract / test writer has a better grasp on what's failing when forgetting / not knowing about `new_with_sudo`.

**Comment by ethanfrey** [comment]
I agree with a better error message here.

**Comment by ethanfrey** [comment]
Huh, I did leave an error message:

```rust
    // this returns an error if the contract doesn't implement sudo
    fn sudo(&self, deps: DepsMut, env: Env, msg: Vec<u8>) -> Result<Response<C>, String> {
        let msg: T4 = from_slice(&msg).map_err(|e| e.to_string())?;
        let res = match &self.sudo_fn {
            Some(sudo) => sudo(deps, env, msg),
            None => return Err("sudo not implemented for contract".to_string()),
        };
        res.map_err(|e| e.to_string())
    }
```

Ah, it seems T4 is String, which doesn't let us parse in. I guess we should use `{}` or such
