### ISSUE TITLE
Ensure all cw20 sends use `Binary` not `Option<Binary>`

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#296]
ex: https://github.com/CosmWasm/cosmwasm-plus/blob/main/packages/cw20/src/msg.rs#L16

This was updated in `cw20-base`, but I forgot the `cw20` spec. Let's check all usage in all packages and ensure they match

**Comment by invis87** [comment]
Even inside `cw20` messages differ :)
`cw20-0.6.1/src/receiver.rs`:
```rust
pub struct Cw20ReceiveMsg {
    pub sender: String,
    pub amount: Uint128,
    pub msg: Binary,
}
```

`cw20-0.6.1/src/msg.rs`:
```rust
    Send {
        contract: String,
        amount: Uint128,
        msg: Option<Binary>,
    },
```
