### ISSUE TITLE
Difference between native and cw20 tokens

### ISSUE THREAD

**Issue by tkowalczyk** [CosmWasm/cosmwasm-plus#297]
Where can I find the description about differences and use cases for both native and cw20 tokens?
Mainly I am asking in the Terra ecosystem context

**Comment by ethanfrey** [comment]
Native tokens are anything the cosmos-sdk chain handles.
Terra's native swap module handles native tokens only.

cw20 tokens are smart contracts and generally only handled by other smart contracts (you cannot pay tx fees in cw20 for example). Most of the DeFi on Terra happily uses both. The lower-level primitives (Cosmos SDK) only use native
