### ISSUE TITLE
Upgrade to CosmWasm 0.15

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#298]
This should be out shortly, and we should update these contracts to show how to do so.

Smart Contracts: 

- [ ] cw1-subkeys
- [ ] cw1-whitelist
- [ ] cw1155-base
- [ ] cw20-atomic-swap
- [x] #302
- [x] #307
- [x] #309
- [ ] #311
- [x] #312
- [ ] cw3-fixed-multisig
- [ ] cw3-flex-multisig
- [ ] cw4-group
- [ ] cw4-stake
- [ ] cw721-base

**Comment by orkunkl** [comment]
- [ ] cw1-subkeys
- [ ] cw1-whitelist
- [ ] cw1155-base
- [ ] cw20-atomic-swap
- [ ] #302
- [ ] cw20-bonding
- [ ] cw20-escrow
- [ ] cw20-ics20
- [ ] cw20-staking
- [ ] cw3-fixed-multisig
- [ ] cw3-flex-multisig
- [ ] cw4-group
- [ ] cw4-stake
- [ ] cw721-base

**Comment by ethanfrey** [comment]
All the rest can be checked except for cw20-icw20, right?
