### ISSUE TITLE
Uprade cw20-ics20 to cw 0.15

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/cosmwasm-plus#311]

**Comment by orkunkl** [comment]
There has been changes on `IbcAcknowledgement`, I stop working on this PR until I get some explanation.

**Comment by ethanfrey** [comment]
This seems to be updated to 0.15.0 already and uses

```rust
        let ack = IbcAcknowledgementWithPacket {
            acknowledgement: IbcAcknowledgement::new(ack_success()),
            original_packet: sent_packet,
        };
```

to create the acks in tests (which is the new format for 0.15.0).

What is left to do?

**Comment by ethanfrey** [comment]
This seems to have been done already by @uint 

Thanks
