### ISSUE TITLE
Messages differ for cw20 & cw20_base

### ISSUE THREAD

**Issue by invis87** [CosmWasm/cosmwasm-plus#320]
`Send` message for `cw20_base` have `msg: Binary`: https://github.com/CosmWasm/cosmwasm-plus/blob/2db7cd9bff474400286a277f6e4b83a55fddef82/contracts/cw20-base/src/msg.rs#L72

`Send` message for `cw20` have `msg: Option<Binary>`: https://github.com/CosmWasm/cosmwasm-plus/blob/2db7cd9bff474400286a277f6e4b83a55fddef82/packages/cw20/src/msg.rs#L19

**Comment by ethanfrey** [comment]
This was previously reported in #296 and just closed with #321

It will be available in v0.7.0. Thank you for pointing it out.
