### ISSUE TITLE
Why cw20-base do not care about minting cap?

### ISSUE THREAD

**Issue by invis87** [CosmWasm/cosmwasm-plus#339]
I found that cw20-base contract do not use `cap` field from: https://github.com/CosmWasm/cosmwasm-plus/blob/9c37cca15bd341d44e3e855f92fcf61b5a125b1e/packages/cw20/src/query.rs#L65

Why?
https://github.com/CosmWasm/cosmwasm-plus/blob/9c37cca15bd341d44e3e855f92fcf61b5a125b1e/contracts/cw20-base/src/contract.rs#L193

**Comment by ethanfrey** [comment]
12 lines below the line you linked, the cap is enforced: https://github.com/CosmWasm/cosmwasm-plus/blob/9c37cca15bd341d44e3e855f92fcf61b5a125b1e/contracts/cw20-base/src/contract.rs#L209-L215

**Comment by invis87** [comment]
@ethanfrey mmm, yes, you are right. But this cap checks `total_cap`, but comment on `cap` field says:
https://github.com/CosmWasm/cosmwasm-plus/blob/9c37cca15bd341d44e3e855f92fcf61b5a125b1e/packages/cw20/src/query.rs#L64 
**issued by the minter**
I understand that in this way. If my `cap = 100`, then at total I can't mint more than 100 tokens. Total supply is a bit different thing, isn't it?

**Comment by ethanfrey** [comment]
> I understand that in this way. If my cap = 100, then at total I can't mint more than 100 tokens. Total supply is a bit different thing, isn't it?

Then the comment should be updated. My intention when writing it, is "mintable with cap" enforced a maximum supply that can be minted in the end (and if you burn some tokens, this allows you to mint more)

**Comment by invis87** [comment]
I didn't know where bug is - in comment on in code. By default I think code is wrong :)

**Comment by ethanfrey** [comment]
I made an issue to close this.

As I designed cw20 and wrote most of the implementations, I am pretty clear what was in my head when I wrote the spec and wrote the code which matches it. If I have tested code and it doesn't match the comments, well the tests are the best guide as to what was expected.
