### ISSUE TITLE
Upgrade rust to 1.53

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/cosmwasm-plus#372]
Working on PR #369 I faced clippy false positive:
> error: this function's return value is unnecessarily wrapped by `Result`

However in this context signature has to be as it is, as the function is later passed as an argument to `impl Fn` of specific signature. This is handled properly in clippy 1.53.

@webmaster128 can we perform such an upgrade?

**Comment by webmaster128** [comment]
What kind of upgrade are you thingking about? I think there are two questions:
- what's the MSRV policy of this repo? We just created this for cosmwasm: https://github.com/CosmWasm/cosmwasm/pull/1038
- Do you want to use a different clippy version than compiler version. I think this is reasonable, but tends to confuse people.

But you can also simply silence the warning at that place and add a comment why you did it.

**Comment by hashedone** [comment]
I know I can just allow the warning, I will do that for now. However as this is fixed already, I don't see a reason why not to bump whole ecosystem version to 1.53 (the newest stable is 1.54 so it seems to be matching minimum supported version as it should be at least one release before newest stable).

**Comment by webmaster128** [comment]
The reason is: we take as much burden as we can on us to avoid any unnecessary disruption of our users (=contract developers), that might be happily compiling with an older version.

**Comment by hashedone** [comment]
Ok, reasonable. Do we consider add a `toolchain.toml` file to make it also easier for developers? I mean I obviously can just override my version but it requires every single dev to keep in mind syncing version he is using with a version supported for contracts, and toolchain file seems to solve that.

**Comment by webmaster128** [comment]
The problem I have with `toolchain.toml` is that it enforces version pinning, which downgrades the compiler version in many cases. I don't want to use an old compiler, just because the project has a relatively low MSRV.

It should not be too hard to keep the project compatible for the range MSRV-latest stable. MSRV here can be defined differently than in cosmwasm if it helps.
