### ISSUE TITLE
Cw20Coin duplication

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/cosmwasm-plus#73]
When I was looking into how to implement cw20 compatible atomic swaps in noticed the contract needs to define a construct for Cw20 tokens. I checked other contracts and saw Cw20Token is defined in [cw20-escrow contract](http://github.com/CosmWasm/cosmwasm-plus/blob/84d9ba6f406ee2c6954afa5fea78ad24865a29e4/contracts/cw20-escrow/src/state.rs#L33-L37). We need to define this struct either in cw20-base or cw20 to prevent duplication in contracts that use cw20

**Comment by maurolacy** [comment]
Same with `Cw20CoinHuman`.
