### ISSUE TITLE
Check for / reject zero amount tokens

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cosmwasm-plus#76]
Add a check for considering zero amounts as missing.

For native coins, filter out zeros, and then ensure then remaining balance has length > 0. Only save the filtered list.

For cw20 coins, reject zero amounts directly. Add a check to also reject such sends in cw20-base.

**Comment by ethanfrey** [comment]
As part of this, let's pull out the [`Balance` helper](https://github.com/CosmWasm/cosmwasm-plus/blob/master/contracts/cw1-subkeys/src/balance.rs) from cw1-subkeys into `cw0` (as it only relies on cosmwasm-std and used by many different protocols).

This already has a [`normalize` function](https://github.com/CosmWasm/cosmwasm-plus/blob/master/contracts/cw1-subkeys/src/balance.rs#L26-L27) which you could use (or add a more efficient `is_empty` one).

This would be a great help to build the higher-level checks for native coins in all contracts.

I would also suggest 2 PRs here: one for the cw20 additions, one for the native coin changes (that I mentioned here)

**Comment by maurolacy** [comment]
Yes, I was taking a look at the subkeys code, and was going to suggest exactly that.

**Comment by ethanfrey** [comment]
This is done with #86 and #87, correct?

**Comment by maurolacy** [comment]
Correct.
