### ISSUE TITLE
Implement Copy for Coin / Vec<Coin>

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cosmwasm-plus#77]
Currently when coins are sent in a message's `sent_funds`, they need to be cloned in order to be used independently of the containing struct (`env` / `env.message`). This makes some code constructs unnatural (or imply extra cloning of the whole structure).

See by example the discussion in https://github.com/CosmWasm/cosmwasm-plus/pull/72#discussion_r484275582 .

Rust errors E0382 / E0505 suggest as an alternative implementing the Copy trait, for the members that need to be accessed independently.

**Comment by ethanfrey** [comment]
I think `Copy` is for non-heap objects, that have no references. `Vec` and `String` can only be `Clone` not `Copy`, which `Coin` and `Vec<Coin>` already are.

The code was fine, I just forgot that we needed to use it twice.

**Comment by maurolacy** [comment]
Fair enough. I think you can always implement you own Copy trait, though. Basically, by re-creating all the objects that are pointers / references in your structs. This is what C++ copy constructors / copy-assignment operators do, by the way.
